version: '3.9'
services:
  postgres:
    image: postgres:14.6
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - soundbridge-db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
volumes:
  soundbridge-db:
    driver: local